import turtle
tartaruga = turtle.Turtle()
tartaruga.shape("turtle")
tartaruga.forward(100)
tartaruga.left(90)
tartaruga.forward(100)
tartaruga.left(90)
tartaruga.forward(100)
tartaruga.left(90)
tartaruga.forward(100)
